[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.build]
cmds = [
  "cd frontend/agendador && npm install && npm run build",
  "cd frontend/admin && npm install && npm run build",
  "cd backend && npm install"
]

[start]
cmd = "cd backend && npm run migrate && npm start"
